### ISSUE TITLE
请问文中的"组件"可不可以理解为structur?

### ISSUE THREAD

**Issue by CharlotteFallices** [phodal/lowcode#1]

**Comment by phodal** [comment]
structur 的定义是？

**Comment by CharlotteFallices** [comment]
我比较喜欢将其翻译为[结构体](https://charlottefallices.github.io/Swift_Chinese_Documents/02_language_guide/09_Structures_And_Classes.html)==

**Comment by phodal** [comment]
那组件的定义你可以重新 Google 了

**Comment by CharlotteFallices** [comment]
我觉得性质差不多嘛==

**Comment by CharlotteFallices** [comment]
组件是[这个](https://baike.baidu.com/item/组件)吧==

**Comment by phodal** [comment]
这个组件可大可小，解释空间比较大。

在后端，你可以视之为 package 的一种形式
在前端，你可以视之为 UI 元素集合。
……

https://stackoverflow.com/questions/13157377/class-vs-package-vs-module-vs-component-vs-container-vs-service-vs-platform-in-j
